# Site settings
title: C-Art Webdesign
email: feedback@videntity.de
description: >
  because your identity matters
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.c-art-web.de/sign" # the base hostname & protocol for your site

# Outputting
permalink: /sign/:year/:month/:day/:title/index.html

# Build settings
markdown: kramdown
